### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/mrgda#39]
- [x] nm summary pass through
- [x] getting start vignette (eric)
- [x] add function for subject comparison
- [x] add AMT DUR RATE test
- [x] requirements and stories
